[Nexus] Increase version to 20.3.2
kodi-pvr/pvr.vdr.vnsi pull request #187
Opened 2022-07-18 15:20 UTC by CastagnaIT

Bump version for inpustream API change
due to:
https://github.com/xbmc/xbmc/pull/21390
https://github.com/xbmc/xbmc/pull/21319

2022-07-18 16:20 UTC, ksooo requested changes

2022-07-18 16:20 UTC, ksooo commented on pvr.vdr.vnsi/changelog.txt
> +v20.3.2
Please increase minor add-on version, not micro. See my comment for pvr.hts.

2022-07-19 07:11 UTC, phunkyfish approved these changes

2022-07-19 09:57 UTC, ksooo approved these changes

2022-09-16 13:45 UTC, AlwinEsch commented
Done by https://github.com/kodi-pvr/pvr.vdr.vnsi/pull/193

2022-09-16 13:45 UTC, closed without merging